"""Public MCP tool callables.

Importing this module registers the complete tool set on the shared application
created by :mod:`comfy_mcp.server._internal`.  The implementation stays private;
this module is the stable Python export surface for direct callers and tests.
"""

from __future__ import annotations

from ._internal import (
    auth_login,
    auth_status,
    discover,
    download,
    download_model,
    emit_partner_workflow,
    fetch_outputs,
    fetch_template,
    free_memory,
    generate_image,
    get_logs,
    get_template,
    install_node,
    job,
    launch_comfyui,
    list_partner_models,
    list_workflow_notes,
    list_workflow_slots,
    node_dependencies,
    nodes,
    partner_generate,
    partner_model_schema,
    project,
    restart_comfyui,
    run_template,
    run_workflow,
    search_models,
    search_templates,
    server_info,
    set_workflow_slot,
    stop_comfyui,
    switch_comfyui_version,
    system_stats,
    update_comfyui,
    upload_file,
    validate_workflow,
    vary_workflow,
    which,
    workflow_deps,
)

__all__ = (
    "auth_login",
    "auth_status",
    "discover",
    "download",
    "download_model",
    "emit_partner_workflow",
    "fetch_outputs",
    "fetch_template",
    "free_memory",
    "generate_image",
    "get_logs",
    "get_template",
    "install_node",
    "job",
    "launch_comfyui",
    "list_partner_models",
    "list_workflow_notes",
    "list_workflow_slots",
    "node_dependencies",
    "nodes",
    "partner_generate",
    "partner_model_schema",
    "project",
    "restart_comfyui",
    "run_template",
    "run_workflow",
    "search_models",
    "search_templates",
    "server_info",
    "set_workflow_slot",
    "stop_comfyui",
    "switch_comfyui_version",
    "system_stats",
    "update_comfyui",
    "upload_file",
    "validate_workflow",
    "vary_workflow",
    "which",
    "workflow_deps",
)
